services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  flink-jobmanager:
    image: flink:1.20.1
    command:
      - jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager

  flink-taskmanager:
    image: flink:1.20.1
    command:
      - taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    depends_on:
      - flink-jobmanager

  heatmap-job:
    build:
      context: .
    image: heatmap-job:latest
    environment:
      - KAFKA_BROKER=kafka:9092
      - REDIS_HOST=redis
    depends_on:
      - kafka
      - flink-jobmanager
    command: >
      flink run -m flink-jobmanager:8081 -c org.example.HeatmapJob /opt/flink/usrlib/geo-heatmap-flink-1.0-SNAPSHOT.jar
